### ISSUE TITLE
Handling of invalid sounds

### ISSUE THREAD

**Issue by arubehn** [cldf-clts/soundvectors#18]
@LinguList I was thinking what would be the best way to handle sounds that we can not parse. Currently, we throw a `ValueError` which breaks the program once a single invalid sound is encountered (including symbols like + or - that frequently occur in cross-linguistic data). 

Would it maybe be better to just raise a warning in such cases and return a vector full of 0? What do you think?

**Comment by LinguList** [comment]
I would prefer to break, to make sure people know their data does not pass. We have already now a behaviour that is quite permissive, as you can see when you write:

```python
c2v = SoundVectors()
c2v.get_vec("my favorite cluster is this one bilabial voiced stop consonant")
```
So extending this even more seems difficult. We can discuss returning a single 0 or an only 0 vector when CALLING the method:

```python
>>> c2v(["a", "b", "c"])
[None, None, None]
```

This means get_vec still throws an error by the call method catches it.

**Comment by LinguList** [comment]
Did you implement this, @arubehn?
